### ISSUE TITLE
Pjax file upload

### ISSUE THREAD

**Issue by sreenadh** [yidas/yii2-bower-asset#1]
Pjax supports file upload since v1.9.3. The current version is 2.0.1. any plan to upgrade this fork. Where can I read the enhancements made in this fork?

https://github.com/defunkt/jquery-pjax/releases/tag/v1.9.3

**Comment by yidas** [comment]
@sreenadh, 

Yii2 uses `yii2-pjax` instead of `jquery-pjax`, so the version is depend on `yii2-pjax`. This package will follow the update with Yii2 version, more information for [yii\widgets\Pjax](http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html).

Cheers.

**Comment by yidas** [comment]
I'm going to close the issue. 

If you have further question, please don't hesitate to let me know.
