### ISSUE TITLE
How to install codemirror-like assets?

### ISSUE THREAD

**Issue by axtho** [yidas/yii2-bower-asset#2]
I had codemirror in my project (conquer/codemirror), which has 
```
public $sourcePath = '@bower/codemirror';
```
in its Asset file. Doing `composer update` or `composer require `produces this error:

```
- Installation request for conquer/codemirror ^2.0 -> satisfiable by conquer/codemirror[2.0].
- conquer/codemirror 2.0 requires bower-asset/codemirror * -> no matching package found.
```
All the other publishers have the same issue. How to deal with this? Was this plugin not supposed to move that to its folder? It has done that with jquery (from Yii2) and others.

Does that mean when we use this plugin we cannot require Assets that rely on @bower/....?

Thanks!

**Comment by yidas** [comment]
Unfortunately, This lib is only support for Yii 2 core bower asset.

[Do not use Bower mixed with Composer project is the goal of this package.](https://github.com/yidas/yii2-bower-asset#limitation)

If you are requiring other Bower packages in Yii2, you could choose [Asset Packagist](https://asset-packagist.org/) solution.

**Comment by axtho** [comment]
Ok. Makes sense. I was mislead by the description of this project, which suggests that it is a cover-all solution.

> Yii 2 official Composer repository solution for Bower Assets

Thanks.
