### ISSUE TITLE
Class yidas\yii2BowerAsset\Installer is not autoloadable, can not call post-package-install script

### ISSUE THREAD

**Issue by ricardoper** [yidas/yii2-bower-asset#3]
Hello,

In some OS and in some conditions I have this error:
`Class yidas\yii2BowerAsset\Installer is not autoloadable, can not call post-package-install script`

I'm working with many Linux variants (Ubuntu, Mint, Fedora, ...), Mac OS X and Windows.

This is error is caused by "installer.php" file because the first letter is lowercase. If I rename this file to "Installer.php" I don't have any issue.

To respect [PSR-4](https://www.php-fig.org/psr/psr-4/) and the good standards, this file must be with the first letter in uppercase.

Best regards,
Ricardo Pereira.

**Comment by yidas** [comment]
Hi @ricardoper,

This issue has been fixed from [version 2.0.13.1](https://github.com/yidas/yii2-bower-asset/releases/tag/2.0.13.1).

Thank you!

**Comment by ricardoper** [comment]
Hello @yidas,

Thanks for the new release. Works as expected...

Best regards,
Ricardo Pereira.
